{% set name = "help2man" %}
{% set version = "1.47.12" %}
{% set sha256 = "7d0ba64cf9d16ec97cc11aafb659b55aa7bdec99072ff2aec5fcecf0fbeab160" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://ftp.gnu.org/gnu/{{ name }}/{{name}}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - 0001-Fix-shebang-in-face-of-short-limits.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - perl
  run:
    - perl

test:
  commands:
    - help2man --help
    - test -f ${PREFIX}/bin/help2man

about:
  home: https://www.gnu.org/software/help2man/
  license: GPL-3.0
  license_family: GPL3
  license_file: COPYING
  summary: 'help2man produces simple manual pages from the --help and --version output of other commands.'
  doc_url: https://www.gnu.org/software/help2man/

extra:
  recipe-maintainers:
    - jjhelmus
    - mariusvniekerk
