{% set name = "help2man" %}
{% set version = "1.47.14" %}
{% set sha256 = "9152596f244d26d250afed878adfe1d42f82fb87c61c5cba230e00fc34c67383" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - 0001-Fix-shebang-in-face-of-short-limits.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - perl
  run:
    - perl

test:
  commands:
    - help2man --help
    - test -f ${PREFIX}/bin/help2man

about:
  home: https://www.gnu.org/software/help2man/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: COPYING
  summary: help2man produces simple manual pages from the --help and --version output of other commands.
  doc_url: https://www.gnu.org/software/help2man/

extra:
  recipe-maintainers:
    - jjhelmus
    - mariusvniekerk
