{% set name = "help2man" %}
{% set version = "1.47.6" %}
{% set sha256 = "d91b0295b72a638e4a564f643e4e6d1928779131f628c00f356c13bf336de46f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://ftp.gnu.org/gnu/{{ name }}/{{name}}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - automake
    - perl
  run:
    - perl

test:
  commands:
    - help2man --help
    - test -f ${PREFIX}/bin/help2man

about:
  home: https://www.gnu.org/software/help2man/
  license: GPL-3.0
  license_family: GPL3
  license_file: COPYING
  summary: 'help2man produces simple manual pages from the --help and --version output of other commands.'
  doc_url: https://www.gnu.org/software/help2man/

extra:
  recipe-maintainers:
    - jjhelmus
