build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: azure, linux_ppc64le: azure}
test_on_native_only: true
bot:
  automerge: true
  run_deps_from_wheel: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
